/**
 * @cam/script-host/sandbox — running untrusted user scripts.
 *
 * THREAT MODEL. A script is untrusted even when the user trusts themselves,
 * because scripts get shared, pasted from forums, and generated by LLMs. The
 * prototype ran `new Function(code)` on the MAIN THREAD, which gave the script
 * the DOM, `fetch`, `localStorage`, and the ability to hang the tab forever.
 * None of that is needed to describe a machining job.
 *
 * WHAT THIS MODULE DOES. It compiles the script with ONLY the capability API
 * bound as named parameters, under strict mode, with a synthetic filename so
 * stack frames can be mapped back to user source. In a browser this runs inside
 * a module worker (no DOM by construction, terminable on timeout); in Node it
 * runs in-process for tests and the CLI.
 *
 * WHAT IT DOES NOT DO, HONESTLY. Deleting globals is defence in depth, not a
 * security boundary: a determined script can still reach objects through
 * prototype chains, and nothing here stops it allocating until the process dies.
 * Real isolation needs a null-origin iframe or a JS-in-JS interpreter, and that
 * is tracked as a follow-up rather than pretended away.
 *
 * Design doc: Part VII.1, VII.2, ADR-006.
 */

import type { Diagnostic } from "@cam/ir";
import { error } from "@cam/ir";
import type { ManufacturingPlan } from "@cam/planner";
import type { ScriptResult } from "./api.js";
import { createScriptApi } from "./api.js";

/** Synthetic filename used when compiling, so stack frames are identifiable. */
export const SCRIPT_FILENAME = "program.cam.js";

/**
 * Globals removed before running a script.
 *
 * Not a sandbox by itself — see the module comment — but it closes the obvious
 * routes and makes accidental use fail loudly rather than silently working.
 */
export const DENIED_GLOBALS = [
  "fetch", "XMLHttpRequest", "WebSocket", "EventSource",
  "importScripts", "indexedDB", "caches", "Notification",
  "localStorage", "sessionStorage", "postMessage",
  "require", "process", "global", "globalThis",
] as const;

export interface RunOptions {
  readonly meshNames?: readonly string[];
  /** Abort after this long. Enforced by the caller in a worker context. */
  readonly timeoutMs?: number;
}

export interface MeshPlacement {
  readonly x: number;
  readonly y: number;
  readonly z: number;
}

export type RunOutcome =
  | { readonly ok: true; readonly plan: ManufacturingPlan;
      readonly diagnostics: readonly Diagnostic[];
      readonly meshName: string | null;
      readonly meshOffset: MeshPlacement }
  | { readonly ok: false; readonly diagnostics: readonly Diagnostic[] };

/**
 * Compile and run a script, returning a plan or diagnostics.
 *
 * A throwing script is a normal outcome, not an exception: the editor shows the
 * message on the offending line. Only a bug in the host would propagate.
 */
export function runScript(source: string, opts: RunOptions = {}): RunOutcome {
  // NOT destructured: `meshName` is a getter, and spreading would evaluate it
  // now — before the script has had a chance to set it.
  const host = createScriptApi({ meshNames: opts.meshNames });
  const { api, harvest } = host;

  const names = Object.keys(api);
  const values = Object.values(api);

  // Shadow denied globals as function parameters bound to undefined. This works
  // even where `delete globalThis.x` does not, because a parameter takes
  // precedence over the global scope inside the function body.
  const shadowed = DENIED_GLOBALS.filter((n) => !names.includes(n));

  let compiled: (...args: unknown[]) => void;
  try {
    compiled = new Function(
      ...names,
      ...shadowed,
      `"use strict";\n${source}\n//# sourceURL=${SCRIPT_FILENAME}`,
    ) as (...args: unknown[]) => void;
  } catch (e) {
    return { ok: false, diagnostics: [syntaxDiagnostic(e)] };
  }

  try {
    compiled(...values, ...shadowed.map(() => undefined));
  } catch (e) {
    const harvested = harvest();
    return {
      ok: false,
      diagnostics: [...harvested.diagnostics, runtimeDiagnostic(e)],
    };
  }

  const result: ScriptResult = harvest();
  if (result.plan.operations.length === 0) {
    return {
      ok: false,
      diagnostics: [
        ...result.diagnostics,
        error("program.noMotion",
          "script produced no operations — call job.face, job.rectPocket, " +
          "job.roughSurface or job.finishSurface"),
      ],
    };
  }

  return {
    ok: true,
    plan: result.plan,
    diagnostics: result.diagnostics,
    meshName: host.meshName,
    meshOffset: host.meshOffset,
  };
}

/* --------------------------- diagnostics ------------------------------- */

function syntaxDiagnostic(e: unknown): Diagnostic {
  const message = e instanceof Error ? e.message : String(e);
  return error("script.error", `syntax error: ${message}`);
}

function runtimeDiagnostic(e: unknown): Diagnostic {
  const message = e instanceof Error ? e.message : String(e);
  const location = locateInScript(e);
  return error("script.error", message,
    location ? { provenance: { operationId: "<script>", script: location } } : {});
}

/**
 * Find the line and column in the USER's script from an error stack.
 *
 * The script is compiled with `//# sourceURL=program.cam.js`, so its frames are
 * identifiable. `new Function` wraps the body, which offsets line numbers by a
 * fixed amount: the generated header is `function anonymous(args...\n) {\n`,
 * putting user line 1 at reported line 3 in V8.
 *
 * This is best-effort by nature. When it cannot find a frame it returns
 * undefined, and the diagnostic simply has no location — which is much better
 * than confidently reporting the wrong line.
 */
export function locateInScript(e: unknown): { line: number; column: number } | undefined {
  if (!(e instanceof Error) || typeof e.stack !== "string") return undefined;

  const pattern = new RegExp(`${SCRIPT_FILENAME}:(\\d+):(\\d+)`);
  for (const frame of e.stack.split("\n")) {
    const m = pattern.exec(frame);
    if (!m) continue;
    const reported = Number.parseInt(m[1], 10);
    const column = Number.parseInt(m[2], 10);
    const line = reported - REPORTED_TO_USER_LINE;
    if (line >= 1) return { line, column };
  }
  return undefined;
}

/**
 * Difference between the line an engine reports and the line the USER wrote.
 *
 * `new Function` wraps the body in a generated header, and we prepend a
 * `"use strict"` line of our own, so reported line numbers are shifted. The
 * exact shift is an engine implementation detail, and a wrong constant silently
 * misreports EVERY error location — so it is measured at load time by throwing
 * from a known user line and seeing what comes back.
 */
const REPORTED_TO_USER_LINE = measureLineOffset();

function measureLineOffset(): number {
  // A one-line "user script" that throws. Its user line number is 1, so the
  // offset is simply whatever the engine reports minus one.
  const userSource = `throw new Error("probe");`;
  try {
    new Function(`"use strict";\n${userSource}\n//# sourceURL=${SCRIPT_FILENAME}`)();
  } catch (e) {
    if (e instanceof Error && typeof e.stack === "string") {
      const m = new RegExp(`${SCRIPT_FILENAME}:(\\d+):`).exec(e.stack);
      if (m) return Number.parseInt(m[1], 10) - 1;
    }
  }
  return 3; // V8's value, used if measurement somehow fails.
}
